config/routes.rb
Rails.application.routes.draw do

  get 'carts/checkout'

  devise_for :users
  get 'welcome' => "page#welcome"
  get 'about' => "page#about"
  get 'contact' => "page#contact"
  get 'checkout' => "page#checkout"

  root "page#welcome"
  resources :products, only: [:index, :show]
  resources :carts do
    member do
      get 'checkout'
    end
  end 
  resources :cart_items, only: [:create]
  namespace :admin do
    resources :products
  end 

end

app/models/cart.rb
class Cart < ActiveRecord::Base
	has_many :cart_items
	accepts_nested_attributes_for :cart_items, :allow_destroy => true

	def add_cart_item(params)
		if (cart_item = cart_items.find_by_product_id params[:product_id])
			cart_item.quantity += params[:quantity].to_i
			cart_item.save
		else
			cart_items.create(params)
		end
	end

	def update!
		cart_items.each(&:update!)
		update_attributes(amount: calculate_amount)
	end

	def calculate_amount
		cart_items.sum("amount")
	end

	def get_size
		cart_items.sum(:quantity)
	end
end

app/models/cart_item.rb
class CartItem < ActiveRecord::Base
	belongs_to :product
	belongs_to :cart

	def update!
		update_attributes(amount: calculate_amount)
	end

	def calculate_amount
		product.price * quantity
	end
end

app/models/image.rb
class Image < ActiveRecord::Base
	has_attached_file :file, :styles => {:thumb => 'x100', :croppable => '600x600>', :big => '1000x1000>'}
	validates_attachment :file, :presence => true,
  :content_type => { :content_type => "image/jpeg" }
	belongs_to :imageable, polymorphic: true
end

app/models/product.rb
class Product < ActiveRecord::Base
	acts_as_taggable
	extend FriendlyId
  friendly_id :name, use: :slugged

  has_many :cart_items
  has_many :images, as: :imageable
  accepts_nested_attributes_for :images, :allow_destroy => true

  def first_image(size = :original)
  	images.first.file.url(size) if images.present?
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
	before_action :authenticate_user!
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < Admin::BaseController
	before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to admin_products_path, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to edit_admin_product_path(@product), notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to admin_products_path, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit!
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_cart

  def current_cart
  	if cookies[:current_cart_id].present?
  		cart = Cart.find cookies[:current_cart_id].to_i
  		if cart.completed_at
  			cart = Cart.create
  			cookies[:current_cart_id] = cart.id
  		end	
  	else
  		cart = Cart.create
  		cookies[:current_cart_id] = cart.id
  	end

  	return cart
  end
end

app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController
	def create
		current_cart.add_cart_item(cart_items_params)
		current_cart.update!
	end

	private
		def cart_items_params
			params.require(:cart_items).permit!
		end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def checkout
  end
end

app/controllers/page_controller.rb
class PageController < ApplicationController
  def welcome
  end

  def about
  end

  def contact
  end

  def checkout
  	
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    if params[:tag]
      @products = Product.tagged_with(params[:tag])
    else
      @products = Product.all
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :price, :tag_list, :images)
    end
end

app/helpers/admin/base_helper.rb
module Admin::BaseHelper
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/admin/products/_form.html.erb
<div class="row">
  <%= form_for([:admin, @product], :html => { :multipart => true } ) do |f| %>
    <div class="col-sm-6">
      <% if @product.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>
          <ul>
          <% @product.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>
      <div class="form-group">
        <%= f.label :name %><br>
        <%= f.text_field :name, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :description %><br>
        <%= f.text_area :description, class: "form-control", rows: "10" %>
      </div>
      <div class="form-group">
        <%= f.label :price %><br>
        <%= f.text_field :price, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :tag_list %><br>
        <%= f.text_field :tag_list, class: "form-control" %>
      </div>
    </div>
    <div class="col-sm-6 images">
      <%= f.label :images %> - <%= link_to "New", "#nogo", id: "add-new-image" %><br>
      <%= f.fields_for :images do |image| %>
        <div class="form-group image">
          <div class="row">
            <div class="col-sm-6">
              <%= image_tag image.object.file.url(:croppable), class: "img-responsive" %><br>
            </div>
            <div class="col-sm-6">
              <%= image.file_field :file %>
            </div>
          </div>
          <%= image.check_box '_destroy' %> <%= image.label :_destroy, "Remove"%>
        </div>
      <% end %>
    </div>
    <div class="col-sm-12">
      <div class="actions">
        <%= f.submit class: "btn btn-primary" %>
      </div>
    </div>
  <% end %>
</div>
<br>
<script type="text/javascript">
  $(document).ready(function(){
    $("#add-new-image").on("click", function(){
      var index = $(".image").size()
      html = "<div class='form-group image'><div class='row'><div class='col-sm-6'><img class='img-responsive' src='/files/croppable/missing.png' alt='Missing'><br></div><div class='col-sm-6'><input type='file' name='product[images_attributes]["+index+"][file]' id='product_images_attributes_"+index+"_file'></div></div></div>"
      $(".images").append(html)
    })
  })
</script>

app/views/admin/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'admin/products/form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', admin_products_path %>

app/views/admin/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Products</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= product.price %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_admin_product_path(product) %></td>
        <td><%= link_to 'Destroy', admin_product_path(product), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to 'New Product', new_admin_product_path %>

app/views/admin/products/new.html.erb
<h1>New Product</h1>

<%= render 'admin/products/form' %>

<%= link_to 'Back', admin_products_path %>

app/views/cart_items/create.js.erb
$("#cart-size").html("<%= current_cart.get_size %>")

app/views/carts/checkout.html.erb
<h1>Carts#checkout</h1>
<p>Find me in app/views/carts/checkout.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Haarp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render "shared/header" %>
<div class="container-fluid">
	<div class="row">
		<div class="col-xs-12">
			<%= yield %>
		</div>
	</div>
</div>


</body>
</html>

app/views/page/about.html.erb
<div class="row about">
	<div class="col-sm-6">
		<%= image_tag "about.jpg", class: "img-responsive" %>
	</div>
	<div class="col-sm-6">
		<h1>About</h1>
		<p>
			Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris auctor iaculis leo, vitae tristique nulla ultrices in. Praesent fermentum, metus quis hendrerit vulputate, est elit iaculis nisl, vel molestie tortor odio vitae dui. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean et iaculis purus.
		</p>
	</div>
</div>

app/views/page/checkout.html.erb
<div class="row checkout">
	<div class="col-sm-12">
		<h1>Checkout</h1>
		<% if current_cart.cart_items.size == 0 %>
			<h1>No Items in Cart</h1>
		<% else %>
			<table class="table">
				<% current_cart.cart_items.includes(:product).each do |cart_item| %>
					<tr>
						<td class="hidden-xs"><%= image_tag cart_item.product.first_image(:thumb) if cart_item.product.images  %></td>
						<td><%= link_to cart_item.product.name.upcase, cart_item.product %></td>
						<td><%= cart_item.quantity %></td>
						<td><%= number_to_currency cart_item.amount %></td>
					</tr>
				<% end %>
			</table>
			<div class="text-right">
				<%= link_to checkout_cart_path(current_cart) do %>
					<div class="btn btn-primary btn-lg">CHECKOUT</div>
				<% end %>
			</div>
		<% end %>
	</div>
</div>

app/views/page/contact.html.erb
<div class="row contact">
	<div class="col-sm-6">
		<%= image_tag "contact.jpg", class: "img-responsive" %>
	</div>
	<div class="col-sm-6">
		<h1>Contact</h1>
		<p>
			Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris auctor iaculis leo, vitae tristique nulla ultrices in. Praesent fermentum, metus quis hendrerit vulputate, est elit iaculis nisl, vel molestie tortor odio vitae dui. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean et iaculis purus.
		</p>
	</div>
</div>

app/views/page/welcome.html.erb
<div class="row">
	<div class="col-sm-6">
		<%= link_to products_path(tag: "canvas") do %>
			<div class="jumbotron text-center">
				<%= image_tag "canvas.jpg", class: "img-responsive" %>
	      <h1>Canvas</h1>
	    </div>
		<% end %>
	</div>
	<div class="col-sm-6">
		<%= link_to products_path(tag: "denim") do %>
			<div class="jumbotron text-center">
				<%= image_tag "denim.jpg", class: "img-responsive" %>
	      <h1>Denim</h1>
	    </div>
		<% end %>
	</div>
</div>

app/views/products/_product.html.erb
<div class="col-sm-4">
	<%= link_to product do %>
		<div class="thumbnail">
		 	<%= image_tag product.first_image %>
		  <div class="caption text-center">
		    <h3><%= product.name.titleize %></h3>
		  </div>
		</div>
	<% end %>
</div>

app/views/products/index.html.erb
<% if params[:tag] %>
  <h1 class="products"><%= params[:tag].titleize %></h1>
<% end %>
<div class="row">
  <% @products.each do |product| %>
    <%= render partial: "products/product", locals: {product: product} %>
  <% end %>
</div>

app/views/products/show.html.erb
<div class="row product">
	<div class="col-sm-6">
		<% @product.images.each do |image| %>
			<%= image_tag image.file.url(:original), class: "img-responsive" %>
		<% end %>
	</div>
	<div class="col-sm-6 detail">
		<p class="name">
		  <%= @product.name.titleize %>
		</p>

		<p class="description">
		  <%= @product.description %>
		</p>

		<p class="price">
		  <%= number_to_currency @product.price %>
		</p>

		<div>
			<%= link_to cart_items_path(cart_items: {product_id: @product.id, quantity: 1}), class: "btn btn-danger btn-lg", method: :post, remote: true do %>
				Add to Cart
			<% end %>
		</div>
	</div>
</div>

app/views/shared/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Haarp", "/", class: "navbar-brand" %>
    </div>
    <ul class="collapse navbar-collapse nav navbar-nav navbar-right">
      <li>
      <%= link_to checkout_path do %>
        CART ( <span id="cart-size"><%= current_cart.get_size %></span> )
      <% end %>
    </ul>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
      	<li><%= link_to "PRODUCTS", welcome_path %></li>
      	<li><%= link_to "ABOUT", about_path %></li>
      	<li><%= link_to "CONTACT", contact_path %></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>